wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.16
    start_time: 1679299138.296637
    t:
      1:
      - 1
      - 5
      - 37
      - 41
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 37
      - 41
      - 51
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.7.16
      5: 0.14.0
      8:
      - 5
config:
  desc: null
  value: /home/splendor/ACTION_HOANG/posec3d_v2/configs/slowonly_r50_ntu60_xsub/limb_xview.yaml
